### ISSUE TITLE
部署到 GitHub Pages

### ISSUE THREAD

**Issue by lingbopro** [Minemetero/Table-Tennis-Counter#1]
毕竟是Web项目，部署一下可以让别人更方便的访问嘛

**Comment by Minemetero** [comment]
欸？你是没看到我已经部署上去了吗？

**Comment by Minemetero** [comment]
ahhhhhhhhhhhhhhhhhhhhhhhhhhhh修好了ahhhhhhhhhhhhhhhhhh,定义一下就行的事ahhhhhhhhhhhhhhhhhh

**Comment by lingbopro** [comment]
> 欸？你是没看到我已经部署上去了吗？
> https://minemetero.github.io/Table-Tennis-Counter/

因为repo链接里没有嘛

**Comment by Minemetero** [comment]
hum?啥意思

**Comment by lingbopro** [comment]
> hum?啥意思

啊  
现在看见了  
`GitHub Mobile` 不知道为啥看不到

**Comment by Minemetero** [comment]
> > hum?啥意思
> 
> 啊 现在看见了 `GitHub Mobile` 不知道为啥看不到

我后知后觉的加上去了，前面没加

**Comment by Minemetero** [comment]
我觉得要加一个功能，在最后一球就要胜利时显示一个消息来提示。然后这个UI也不太好看要调一调。。。。
