### ISSUE TITLE
Suggestion: Tidy Up Commits

### ISSUE THREAD

**Issue by lingbopro** [Minemetero/Table-Tennis-Counter#10]
现在的提交列表太乱了...  
我觉得需要整顿一下  
比如新建个分支，在这个分支里整理，整理完再把这个分支设为主分支什么的

**Comment by Minemetero** [comment]
把你也给Assign进去 :)

**Comment by lingbopro** [comment]
> 把你也给Assign进去 :)

啊…

**Comment by lingbopro** [comment]
任务艰巨啊

**Comment by Minemetero** [comment]
ahhh

**Comment by lingbopro** [comment]
啊？

Medal of Honor？

**Comment by Minemetero** [comment]
鼓励你帮我写代码 🥇

**Comment by lingbopro** [comment]
搞了个`tidy`分支  
接下来可以准备与`master`的交接工作了

**Comment by lingbopro** [comment]
@Minemetero 请求一下你的意见  
要不要把`tidy`改名为`main`然后设成主分支  
要是你觉得可以那我就干了

**Comment by lingbopro** [comment]
@Minemetero 如果你觉得可以就直接设置罢  
我待会把`tidy`分支改个名

**Comment by Minemetero** [comment]
我都没意识到多了个分支

**Comment by lingbopro** [comment]
> 我都没意识到多了个分支

所以说改不改主分支？

**Comment by Minemetero** [comment]
改了把原来的删掉

**Comment by Minemetero** [comment]
等一下你用PR拉过去然后main删掉

**Comment by lingbopro** [comment]
> 等一下你用PR拉过去然后main删掉

啊？  
那样的话`master`还是有之前的提交记录  
而且由于`main`最开始是空分支，所以没办法合并或者建PR

**Comment by lingbopro** [comment]
![image](https://github.com/Minemetero/Table-Tennis-Counter/assets/148617407/535c618a-94ff-43c0-a244-ce0e33822a8c)

真服了  
又push不上去

**Comment by lingbopro** [comment]
> > 等一下你用PR拉过去然后main删掉
> 
> 啊？ 那样的话`master`还是有之前的提交记录 而且由于`main`最开始是空分支，所以没办法合并或者建PR

你看，这个并不了  

![image](https://github.com/Minemetero/Table-Tennis-Counter/assets/148617407/163aba2c-aea9-4b8e-8765-7a16fcc1e8fb)

所以说就是`main`和`master`今天只能活一个（

**Comment by Minemetero** [comment]
为啥会是空分支

**Comment by Minemetero** [comment]
那你把东西保存把main给删了再创建一个基于master的分支，然后放上去，最后合并 （我对合并是有执着的）

**Comment by Minemetero** [comment]
而且你知道这意味着什么吗？一旦main分支变为主题仓库默认所有代码是你的了 :(

**Comment by lingbopro** [comment]
> 那你把东西保存把main给删了再创建一个基于master的分支，然后放上去，最后合并 （我对合并是有执着的）

基于`master`估计不行，但是你可以再建一个空分支，把`main`的代码放进去，再设成主分支

**Comment by lingbopro** [comment]
> 为啥会是空分支

因为如果基于`master`会带上之前的提交记录，会导致很乱

**Comment by Minemetero** [comment]
你这Contributing 的文件。。。我看了都晕

**Comment by Minemetero** [comment]
要那么多规则干啥嘛。。。

**Comment by lingbopro** [comment]
~~当然还有一个办法就是开一个新repo~~

**Comment by Minemetero** [comment]
这部把人家都给劝退了

**Comment by Minemetero** [comment]
我不接受

**Comment by lingbopro** [comment]
> 你这Contributing 的文件。。。我看了都晕

其实不难，就是`类型+标题+空行+内容`  
你要是觉得多我可以删点

**Comment by lingbopro** [comment]
所以说你是觉得一定要基于`master`是吗  
要非得这样其实也行  
你要是这么觉得那我就换个方式:)

**Comment by lingbopro** [comment]
> 所以说你是觉得一定要基于`master`是吗 要非得这样其实也行 你要是这么觉得那我就换个方式:)

反正repo是你的，你说了算:>

**Comment by Minemetero** [comment]
没事覆盖就覆盖之前我一个Bug 10几个commit我自己都看不下去

**Comment by lingbopro** [comment]
> 没事覆盖就覆盖之前我一个Bug 10几个commit我自己都看不下去

所以还是基于`master`？

**Comment by Minemetero** [comment]
main和master就一个名字随便啦

**Comment by lingbopro** [comment]
> 没事覆盖就覆盖之前我一个Bug 10几个commit我自己都看不下去

事实证明，在`dev`分支测试很重要（

**Comment by lingbopro** [comment]
> main和master就一个名字随便啦

我的意思是说我们是新建空分支还是基于`master`

**Comment by Minemetero** [comment]
额新建分支把其他的都删空都行

**Comment by lingbopro** [comment]
> 额新建分支把其他的都删空都行

那得你创建吧？  
```shell
git checkout --orphan <Branch Name>
```

**Comment by Minemetero** [comment]
哈？

**Comment by Minemetero** [comment]
没听懂

**Comment by lingbopro** [comment]
话说是不是可以这样  
你创建一个基于`main`的分支  
然后把`main`删了  
再把你的分支改个名然后设为主分支

**Comment by lingbopro** [comment]
> 没听懂

就是你在目录里执行那个命令（`<Branch Name>`是要创建的分支名），就可以创建空分支

**Comment by Minemetero** [comment]
名字叫啥

**Comment by lingbopro** [comment]
> 名字叫啥

随便，反正之后可以改

**Comment by lingbopro** [comment]
这个...要不关了吧

**Comment by lingbopro** [comment]
哎…一直没动静  

不如还继续将就用`master`吧，整理太费事了（

**Comment by Minemetero** [comment]
en

**Comment by Minemetero** [comment]
搞定了心满意足了吧：）

**Comment by lingbopro** [comment]
> 搞定了心满意足了吧：）

挺好:)

**Comment by Minemetero** [comment]
yeahhhhhhhhhh

**Comment by lingbopro** [comment]
> yeahhhhhhhhhh

我可以准备开始工作了:)  
不过得过会  
我现在在外面

**Comment by Minemetero** [comment]
我搞搞我自己的LazyPy这个项目永远都不会过时

**Comment by Minemetero** [comment]
再搞搞你的hosts，差不多可以出了

**Comment by Minemetero** [comment]
再水一个小版本号

**Comment by lingbopro** [comment]
![Screenshot_20240621_152916_com.github.android.jpg](https://github.com/Minemetero/Table-Tennis-Counter/assets/148617407/30fb0b2d-87ba-4d8a-ae96-d659418c7cd6)

@Minemetero 你不要这样啊！！！！！！

你这样我就前功尽弃了啊啊啊啊啊！！！！！

**Comment by lingbopro** [comment]
> ![Screenshot_20240621_152916_com.github.android.jpg](https://github.com/Minemetero/Table-Tennis-Counter/assets/148617407/30fb0b2d-87ba-4d8a-ae96-d659418c7cd6)
> 
> @Minemetero 你不要这样啊！！！！！！
> 
> 你这样我就前功尽弃了啊啊啊啊啊！！！！！

忍不了忍不了啊

干脆再创建一个以`dev`为基础的分支再设为主分支罢

这样的提交记录真的太难受了啊啊啊啊啊

**Comment by lingbopro** [comment]
> > ![Screenshot_20240621_152916_com.github.android.jpg](https://github.com/Minemetero/Table-Tennis-Counter/assets/148617407/30fb0b2d-87ba-4d8a-ae96-d659418c7cd6)
> > 
> > @Minemetero 你不要这样啊！！！！！！
> > 
> > 你这样我就前功尽弃了啊啊啊啊啊！！！！！
> 
> 忍不了忍不了啊
> 
> 干脆再创建一个以`dev`为基础的分支再设为主分支罢
> 
> 这样的提交记录真的太难受了啊啊啊啊啊

忍不了啊，必须重新打开issue

**Comment by lingbopro** [comment]
> > > ![Screenshot_20240621_152916_com.github.android.jpg](https://github.com/Minemetero/Table-Tennis-Counter/assets/148617407/30fb0b2d-87ba-4d8a-ae96-d659418c7cd6)
> > > 
> > > @Minemetero 你不要这样啊！！！！！！
> > > 
> > > 你这样我就前功尽弃了啊啊啊啊啊！！！！！
> > 
> > 忍不了忍不了啊
> > 
> > 干脆再创建一个以`dev`为基础的分支再设为主分支罢
> > 
> > 这样的提交记录真的太难受了啊啊啊啊啊
> 
> 忍不了啊，必须重新打开issue

@Minemetero ！！！
@Minemetero ！！！

你说句话啊

**Comment by Minemetero** [comment]
e

**Comment by lingbopro** [comment]
> e

啊～

舒服了
VSCode，启动！

**Comment by Minemetero** [comment]
我更新了README.md你要pull一下

**Comment by lingbopro** [comment]
> 我更新了README.md你要pull一下

艹
刚clone下来没多久就发现你改了readme

**Comment by Minemetero** [comment]
> > e
> 
> 啊～
> 
> 舒服了 VSCode，启动！

开工了但没完全开工是吧

**Comment by lingbopro** [comment]
@Minemetero 我发PR了  
你看看  

这个PR费了我至少2.5个小时  
说开工逝肯定会开工的~
