### ISSUE TITLE
Bug: Unright Hint

### ISSUE THREAD

**Issue by Minemetero** [Minemetero/Table-Tennis-Counter#12]
当我打开语言界面点击English，它显示的信息是Theme set to auto

**Comment by lingbopro** [comment]
啊
估计是忘改onclick了

**Comment by lingbopro** [comment]
不对啊
我这没复现
你说的那个是页面加载的时候的那个snackbar吧
由于更改语言需要刷新
所以就触发了页面加载的那个snackbar
