### ISSUE TITLE
Suggestion: Show the serve side

### ISSUE THREAD

**Issue by Minemetero** [Minemetero/Table-Tennis-Counter#15]
从竞争对手那学的，一律采用新版的规则！！！
对手那个使用的旧版规则，现在不需要抢发球权

**Comment by lingbopro** [comment]
em

**Comment by lingbopro** [comment]
我加了中文翻译

有中文就舒服多了啊

**Comment by Minemetero** [comment]
ah

**Comment by lingbopro** [comment]
所以具体怎么做呢

我对乒乓球不熟啊

**Comment by Minemetero** [comment]
我们的竞争对手执迷于TypeScript对我们没有威胁

**Comment by Minemetero** [comment]
额你可以去维基百科上康康

**Comment by Minemetero** [comment]
> 我加了中文翻译
> 
> 有中文就舒服多了啊

你要习惯看英语

**Comment by lingbopro** [comment]
> > 我加了中文翻译
> > 
> > 有中文就舒服多了啊
> 
> 你要习惯看英语

虽然但是，还是本地化舒服:)

**Comment by lingbopro** [comment]
我从[百度百科上](https://baike.baidu.com/item/%E4%B9%92%E4%B9%93%E7%90%83%E6%AF%94%E8%B5%9B%E8%A7%84%E5%88%99/10980764#13)看到了这个：

> 在获得每2分之后，接发球方即成为发球方,依此类推，直至该局比赛结束， 或者直至双方比分都达到10分或实行轮换发球法，这时，发球和接发次序仍然不变，但每人只轮发一分球。 [2]

**Comment by Minemetero** [comment]
轮换发球法

**Comment by lingbopro** [comment]
> 轮换发球法

就是先第一个人发，然后第二个人发，接着第一个人发，再第二个人发...

是这种吗

**Comment by Minemetero** [comment]
简单粗暴

**Comment by lingbopro** [comment]
> 简单粗暴

雀食简单

或者我们不如多提供一些方式，让用户选择

**Comment by Minemetero** [comment]
好我同意你 ：）

**Comment by lingbopro** [comment]
> 好我同意你 ：）

emm

我觉得目前这个计分的UI还需要改进啊
（因为我想加个计时器

**Comment by lingbopro** [comment]
> 好我同意你 ：）

emm

我觉得目前这个计分的UI还需要改进啊
（因为我想加个计时器

**Comment by lingbopro** [comment]
开干

先切去dev分支，免得因为冲突问题而炸掉

**Comment by lingbopro** [comment]
emmm

还得更新一下dev

**Comment by lingbopro** [comment]
我现在遇到了一个问题

我要弄一个输入框，让用户输入总分每达到几分就轮换，但是这个输入框叫什么呢...

**Comment by lingbopro** [comment]
> 我现在遇到了一个问题
> 
> 我要弄一个输入框，让用户输入总分每达到几分就轮换，但是这个输入框叫什么呢...

我觉得可以叫 `每次轮换分数`

**Comment by Minemetero** [comment]
轮换发球时
