### ISSUE TITLE
Bug: Unbelievable Boxes

### ISSUE THREAD

**Issue by Minemetero** [Minemetero/Table-Tennis-Counter#18]
![Screenshot 2024-06-24 172717](https://github.com/Minemetero/Table-Tennis-Counter/assets/156386015/ce804417-a7e9-48a9-8553-cbb7eab9ac17)
此处无声胜有声

**Comment by lingbopro** [comment]
啊？
啊？？
啊？？？

你这咋复现的

**Comment by lingbopro** [comment]
不对劲啊
我待会看看

**Comment by lingbopro** [comment]
我在本地跑没出问题啊
怎么部署上去就炸了呢

**Comment by lingbopro** [comment]
搞明白了

肯定是git干的（

**Comment by lingbopro** [comment]
这就对了
