### ISSUE TITLE
Emergency Bug: Serve side doesn't work well

### ISSUE THREAD

**Issue by Minemetero** [Minemetero/Table-Tennis-Counter#22]
![Screenshot 2024-06-26 193555](https://github.com/Minemetero/Table-Tennis-Counter/assets/156386015/af470be2-10a2-482f-ac21-48513b331ae6)
![Screenshot 2024-06-26 193600](https://github.com/Minemetero/Table-Tennis-Counter/assets/156386015/a2417696-ca5f-44b4-8342-79e3d0f7ad99)
![Screenshot 2024-06-26 193606](https://github.com/Minemetero/Table-Tennis-Counter/assets/156386015/aecfe683-6db3-4cd4-ae11-411cdfa3b1af)
![Screenshot 2024-06-26 193611](https://github.com/Minemetero/Table-Tennis-Counter/assets/156386015/3b141a8d-acfb-4bf4-b0ea-facd9c7f41bc)
![Screenshot 2024-06-26 193616](https://github.com/Minemetero/Table-Tennis-Counter/assets/156386015/f121a8a7-49d5-4e8a-873b-da7a33dd15d9)

**Comment by lingbopro** [comment]
![image](https://github.com/Minemetero/Table-Tennis-Counter/assets/148617407/3265346b-e4f7-4985-94d7-2a1278cf95a6)

我这挺好的，没复现啊

**Comment by lingbopro** [comment]
> 不知道为什么我的本地html陷入了无限重载...
> 
> 我怀疑是扩展干的

最后发现是油猴干的...  
但是关了这个就好了  
![image](https://github.com/Minemetero/Table-Tennis-Counter/assets/148617407/8451ddf9-59ae-481f-bb6d-b4fdd8a0eff6)  
我用的油猴的beta版，看来逝出bug了...

**Comment by lingbopro** [comment]
> > 不知道为什么我的本地html陷入了无限重载...
> > 我怀疑是扩展干的
> 
> 最后发现是油猴干的... 但是关了这个就好了 ![image](https://private-user-images.githubusercontent.com/148617407/343174272-8451ddf9-59ae-481f-bb6d-b4fdd8a0eff6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MDg0NjAsIm5iZiI6MTcxOTQwODE2MCwicGF0aCI6Ii8xNDg2MTc0MDcvMzQzMTc0MjcyLTg0NTFkZGY5LTU5YWUtNDgxZi1iYjZkLWI0ZmRkOGEwZWZmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNlQxMzIyNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00M2NlYWNkZDcwMTIyZjY5MzM4ZWY3Mzc5YmUyY2I5NTYyZjAxYTM3NWVjYTNhZmYwNzYzZDRiNTI4MWJiZjBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HkCA1CieCZW6ILWX4mJsVklbTdaHJTet0Z6-r4f8Cfk) 我用的油猴的beta版，看来逝出bug了...

不对劲啊  
还是陷入了刷新  
我打算重启一下浏览器  
（毕竟Windows下的故障排查就是重启

**Comment by Minemetero** [comment]
(((

**Comment by Minemetero** [comment]
![Screenshot 2024-06-27 090636](https://github.com/Minemetero/Table-Tennis-Counter/assets/156386015/2a14e6ba-ca3b-479c-a856-41442e528bed)
![Screenshot 2024-06-27 090642](https://github.com/Minemetero/Table-Tennis-Counter/assets/156386015/ee161224-a9ea-4550-9801-9d1f5f68db3d)
![Screenshot 2024-06-27 090647](https://github.com/Minemetero/Table-Tennis-Counter/assets/156386015/c3c291a5-bb57-464c-95eb-29abb10839b1)

**Comment by Minemetero** [comment]
就是有问题（

**Comment by lingbopro** [comment]
![Screenshot_20240627_084650_com.microsoft.emmx.jpg](https://github.com/Minemetero/Table-Tennis-Counter/assets/148617407/e1696377-a235-4b83-a429-0707979c6c19)

这个界面还得做移动端优化  
下面的Score完全点不到  
关键是还不允许滚动

**Comment by lingbopro** [comment]
https://github.com/Minemetero/Table-Tennis-Counter/assets/148617407/0b4455dd-894c-4d1b-832c-9cb497fbc61f

无法复现，斩了（

**Comment by lingbopro** [comment]
https://github.com/Minemetero/Table-Tennis-Counter/assets/148617407/4077073e-b8dc-494a-8e40-66a68985e34c

无法复现，斩了（

**Comment by Minemetero** [comment]
你试试如果添加3个人就会有问题

**Comment by lingbopro** [comment]
> 你咋一句话不说我还想着视频里有你的声音

录屏的啊，没开麦克风  
而且也没必要

**Comment by lingbopro** [comment]
> 你试试如果添加3个人就会有问题

回头我试试
