### ISSUE TITLE
Emergency: Sober Breaking Changes

### ISSUE THREAD

**Issue by lingbopro** [Minemetero/Table-Tennis-Counter#25]
# 我找到界面问题的罪魁祸首了！！！  
就是Sober进行了大更改导致的  
<details>
  <summary>原问题图片</summary>
  <img width="524" alt="image" src="https://github.com/Minemetero/Table-Tennis-Counter/assets/148617407/653076a4-7a9b-4c1f-8089-52c66bf435f2">
</details>

## 文本框  
文本框我们使用`display: block`来占满一行  
然而文档现在使用`display: grid`，因此导致了布局大小问题  

<img width="524" alt="image" src="https://github.com/Minemetero/Table-Tennis-Counter/assets/148617407/2e17b0ee-817b-4010-9bbc-0d55195da003">

## 顶栏
更改了标签名（由`<s-top-app-bar>`改成`<s-appbar>`），导致无样式  

<img width="525" alt="image" src="https://github.com/Minemetero/Table-Tennis-Counter/assets/148617407/5be9edab-4f7f-4111-8bde-90a6476f2e6c">

## 菜单
同顶栏，也是改名了  

<img width="522" alt="image" src="https://github.com/Minemetero/Table-Tennis-Counter/assets/148617407/06b9df11-ba5d-4fa1-99ab-6b535e24fe89">

-----

反正就是尽快修吧

**Comment by Minemetero** [comment]
回首 我们的issue真多
