### ISSUE TITLE
Emergency: Language System Broken

### ISSUE THREAD

**Issue by Minemetero** [Minemetero/Table-Tennis-Counter#29]
![image_2024-07-09_132113460](https://github.com/Minemetero/Table-Tennis-Counter/assets/156386015/d18095ae-9ca3-427e-a2db-9b3de1ec1f43)
中文界面坏了

**Comment by lingbopro** [comment]
啊？？？？？

**Comment by lingbopro** [comment]
看我在 #28 的审查

就是因为你把装工具提示的div删了还没删结束标签，导致元素解析出问题，再加上无法弹出工具提示，就报错了

**Comment by lingbopro** [comment]
@Minemetero

**Comment by Minemetero** [comment]
:(

**Comment by Minemetero** [comment]
我以为那东西没用

**Comment by lingbopro** [comment]
你没把这个div加回来啊

**Comment by Minemetero** [comment]
加回来了啊

**Comment by lingbopro** [comment]
没有啊

还是有一个孤立的`</div>`

**Comment by Minemetero** [comment]
a?

**Comment by Minemetero** [comment]
GIthub的问题你看dev分支已经改来了

**Comment by lingbopro** [comment]
o

**Comment by Minemetero** [comment]
哦？
