### ISSUE TITLE
Bug: Update Sober Version

### ISSUE THREAD

**Issue by Minemetero** [Minemetero/Table-Tennis-Counter#33]
更新Sober版本
对新版本进行适配

**Comment by Minemetero** [comment]
气死我了啊

**Comment by Minemetero** [comment]
我改了版本号，那个sober改了啥，Picker的大小不太对劲啊，那个去CSS file里面修改结果雷打不动

**Comment by Minemetero** [comment]
--picker-border-width	
我改不动这个参数啊，你这CSS里面还设了啥

**Comment by lingbopro** [comment]
> --picker-border-width	
> 我改不动这个参数啊，你这CSS里面还设了啥

可能是Sober改了变量名？可以去看代码（）

**Comment by lingbopro** [comment]
> > --picker-border-width	
> > 我改不动这个参数啊，你这CSS里面还设了啥
> 
> 可能是Sober改了变量名？可以去看代码（）

**这个确实是Sober的问题**

-----

https://github.com/apprat/sober/blob/main/src%2Fpicker.ts#L16-L26

这里初始化了变量

-----

https://github.com/apprat/sober/blob/main/src%2Fpicker.ts#L35-L37

但是根本没有被应用到Field上

**Comment by Minemetero** [comment]
666
快去上报issue

**Comment by lingbopro** [comment]
啊？关了？

**Comment by Minemetero** [comment]
Sober的问题我们这个暂时升级不了

**Comment by Minemetero** [comment]
如果升级彻底坏掉

**Comment by Minemetero** [comment]
必须得再次打开，现在sober删除了原来的版本，整个页面坏了

**Comment by Minemetero** [comment]
@lingbopro 修！修！Add Player!

**Comment by lingbopro** [comment]
啊？

**Comment by lingbopro** [comment]
在NPM上删了原来的版本？？什么操作😕

**Comment by lingbopro** [comment]
确实，Sober 的版本少了很多，目前最保险的方法是降级到 [`0.2.2`](https://www.npmjs.com/package/sober/v/0.2.2)

**Comment by lingbopro** [comment]
[`0.4.2`](https://www.npmjs.com/package/sober/v/0.4.2) 是最后一个可以完美兼容的版本

（好像从 [`0.5.0`](https://www.npmjs.com/package/sober/v/0.5.0) 开始主题色改了

**Comment by lingbopro** [comment]
目前看来（应该）没有什么问题

**Comment by Minemetero** [comment]
oh?

**Comment by Minemetero** [comment]
![image_2024-11-16_155313767](https://github.com/user-attachments/assets/d8972c9e-166e-48da-93ef-4966e2d30642)
这都缩水了你告诉我是完美兼容

**Comment by Minemetero** [comment]
。。。。

**Comment by lingbopro** [comment]
> ![image_2024-11-16_155313767](https://private-user-images.githubusercontent.com/156386015/386826221-d8972c9e-166e-48da-93ef-4966e2d30642.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NDMwMDgsIm5iZiI6MTczMTc0MjcwOCwicGF0aCI6Ii8xNTYzODYwMTUvMzg2ODI2MjIxLWQ4OTcyYzllLTE2NmUtNDhkYS05M2VmLTQ5NjZlMmQzMDY0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNlQwNzM4MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOGE2ODkyMDlkZmQ4NzlkNTBmZWI3YjA2NTNhNzU0ODI0YmRiMzc4NzZjMWJhNDJiZWNlMTVmYmM4MmFhMDQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.aoTDYUR_-ol0ikLMUAly8_Y0_2ZNIDbhiSyguCmMlaQ) 这都缩水了你告诉我是完美兼容

UI没炸就行（）

**Comment by lingbopro** [comment]
Sober 太不稳定了，要不改用别的吧（

**Comment by Minemetero** [comment]
> Sober 太不稳定了，要不改用别的吧（

这句话。。似曾相识。。。

**Comment by Minemetero** [comment]
![Screenshot 2024-11-21 091523](https://github.com/user-attachments/assets/704e72b9-f4cc-44fb-bc97-3626cea96572)
原来如此。。。

**Comment by lingbopro** [comment]
我打算离开Sober自立门户了

（开源就是这点好，一言不合就可以fork

**Comment by lingbopro** [comment]
我的新组件库制作中...

目前进度：重写 Sober 的核心部分

**Comment by lingbopro** [comment]
绷

![image](https://github.com/user-attachments/assets/a34ee0b4-b335-4408-8fad-d9bca35dc3d8)

**Comment by Minemetero** [comment]
> 我的新组件库制作中...
> 
> 目前进度：重写 Sober 的核心部分

什么时候你技术那么叼了。。。

**Comment by lingbopro** [comment]
> > 我的新组件库制作中...
> > 目前进度：重写 Sober 的核心部分
> 
> 什么时候你技术那么叼了。。。

其实也不难（）  
我现在已经重写完核心了  

仓库里已经有了4个提交  
（不过我没公开仓库

**Comment by lingbopro** [comment]
Sober的提交历史挺幽默

一大堆 `bugfix`

甚至 [第一个提交](https://github.com/apprat/sober/commit/fdc494ad61517d9fb940aa2bc6ddc5fad190ef6f) 的标题也是 `bugfix`
