### ISSUE TITLE
Suggestion: Pop-UP on Last Boal

### ISSUE THREAD

**Issue by Minemetero** [Minemetero/Table-Tennis-Counter#5]
在最后一球时发出提示比如说Match Point

**Comment by lingbopro** [comment]
所以此处的最后一球是指本局胜利吗

**Comment by Minemetero** [comment]
嗯~ o(*￣▽￣*)o

**Comment by Minemetero** [comment]
那个Cursor你可以看看，与AI结合的IDE,你可以直接导入VSCode的配置，挺有意思的

**Comment by lingbopro** [comment]
> 那个Cursor你可以看看，与AI结合的IDE,你可以直接导入VSCode的配置，挺有意思的

那个啊，我知道

**Comment by Minemetero** [comment]
> > 那个Cursor你可以看看，与AI结合的IDE,你可以直接导入VSCode的配置，挺有意思的
> 
> 那个啊，我知道

我今天开始使用

**Comment by Minemetero** [comment]
lmao
