### ISSUE TITLE
Suggestion: Language Support

### ISSUE THREAD

**Issue by Minemetero** [Minemetero/Table-Tennis-Counter#6]
增加多语言支持，比如说在右上角增加语言的切换图标，可以换成中文等

**Comment by lingbopro** [comment]
这个我也想过  
实现起来也不是很难，回头我逝逝（

**Comment by lingbopro** [comment]
我的想法是这样的：  

有一个对象，存储了语言的信息（比如说这样：
```javascript
const languages = {
    'zh-CN': [
        ...
    ],
    'en-US': [
        ...
    ]
}
```

然后有一个`lang(key)`函数，用来查找当前语言的键`key`对应的文本  

当然，还有一个变量用来存储当前语言

**Comment by Minemetero** [comment]
:) 我现在被我的README搞得死去活来

**Comment by Minemetero** [comment]
Action一直失败

**Comment by lingbopro** [comment]
> :) 我现在被我的README搞得死去活来

啊？？？

**Comment by lingbopro** [comment]
> Action一直失败

哦  

那个热力图贪吃蛇事罢

**Comment by Minemetero** [comment]
不是的呢

**Comment by Minemetero** [comment]
我在倒腾新东西

**Comment by Minemetero** [comment]
你不上学吗。。。

**Comment by lingbopro** [comment]
> 你不上学吗。。。

我考完期末考试力，不用去力（大喜

**Comment by Minemetero** [comment]
:( 大为不满

**Comment by Minemetero** [comment]
我们学校用电脑，我偷偷在这和你聊天。。。

**Comment by lingbopro** [comment]
> :( 大为不满
> 我们学校用电脑，我偷偷在这和你聊天。。。

呃啊  
我之前也这么干的  
不过现在告别学校的seewo了  
_我还在学校电脑上给之后的有缘人留了个Markdown（（（_

**Comment by Minemetero** [comment]
ahhhhhhhhhhhhhh我成功啦ahhhhhhhhhhhhhhhhhh

**Comment by Minemetero** [comment]
> > :( 大为不满
> > 我们学校用电脑，我偷偷在这和你聊天。。。
> 
> 呃啊 我之前也这么干的 不过现在告别学校的seewo了 _我还在学校电脑上给之后的有缘人留了个Markdown（（（_

为啥告别seewo了

**Comment by lingbopro** [comment]
> ahhhhhhhhhhhhhh我成功啦ahhhhhhhhhhhhhhhhhh

ohhhhh

**Comment by Minemetero** [comment]
实在是坑，坑太多了

**Comment by Minemetero** [comment]
留了个Markdown?咋留的，留的啥

**Comment by Minemetero** [comment]
期末考试你考的咋样。。。

**Comment by lingbopro** [comment]
> 留了个Markdown?咋留的，留的啥

就是简单留了个联系方式

**Comment by lingbopro** [comment]
> 期末考试你考的咋样。。。
> 无论如何，祝你好运

我…我不到啊（
